cat >build/src/env.json <<EOL
{
"LALOG_LEVEL": "$LALOG_LEVEL",
"LOGGLY_TOKEN": "$LOGGLY_TOKEN",
"PLANT_IMAGE_COMPLETE": "$PLANT_IMAGE_COMPLETE",
"PLANT_IMAGE_HOST": "$PLANT_IMAGE_HOST",
"PLANT_IMAGE_PORT": "$PLANT_IMAGE_PORT"
}
EOL