cat >build/src/env.json <<EOL
{
"PLANT_IMAGE_COMPLETE": "$PLANT_IMAGE_COMPLETE",
"PLANT_IMAGE_HOST": "$PLANT_IMAGE_HOST",
"PLANT_IMAGE_PORT": "$PLANT_IMAGE_PORT",
"LOGGLY_TOKEN": "$LOGGLY_TOKEN"
}
EOL